workflows:
  web-build:
    name: Build Static Website
    environment:
      vars:
        NODE_VERSION: "18.16.0"
      node: $NODE_VERSION
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build website
        script: |
          npm run build
    artifacts:
      - build/**
